### PR TITLE
Add support for time-1.6

### PR DESCRIPTION
**Pull request by ryantrinkle**

### CODE REVIEW

**Comment by ryantrinkle** [comment]
@ygale Anything I can do to move this forward?

**Comment by ygale** [comment]
A modified version of this PR, using a cabal flag instead of CPP, was implemented in timezone-series-0.1.6.1.

**Comment by ygale** [comment]
Ryan, a belated thanks!

**Comment by ryantrinkle** [comment]
@ygale No problem :)

**Pull request closed without merging**
